[package]
name = "para-genesis-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.9"
macroquad = "0.4.5"
noise = "0.8.2"
rand = "0.8.5"
